language: node_js
node_js:
  - "12.8.1"
script:
  -
install:
  - npm install
  - npm run build
  - cd functions
  - npm install
  - cd ..
deploy:
  verbose: true
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "timetracker-one-app"
